name: Build Setup
description: Setup for standard Java builds

inputs:
  update-cache:
    description: If cache should be updated
    required: false
    default: 'false'
  ref:
    description: 'Ref to checkout'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref || github.ref }}
    - name: Set up JDK
      uses: actions/setup-java@v4
      env:
        REF: ${{ inputs.ref || github.ref }}
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-write-only: ${{ inputs.update-cache }}
        cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/1.19.2' }}
        add-job-summary: 'on-failure'
