modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "Mekanism Extras"
    displayURL= "https://www.curseforge.com/members/lost_myself8/projects"
    logoFile= "logo.png"
    credits="Thank you to all those who have made any contributions to this mod"
    authors = "${mod_authors}"
    description = '''${mod_description}'''

[[mixins]]
    config = "mekextra.mixins.json"
    description = '''${mod_description}'''

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "mekanism"
    type = "required"
    versionRange = "[10.7.14]"
    ordering = "AFTER"
    side = "BOTH"
